services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
    ports:
      - "4566:4566"  # Main Localstack port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Mount Docker socket
